## ==================================================================
## List of disease-associated rsIDs and corresponding lincRNAs from 
## [LincSNP](http://210.46.85.180:8080/LincSNP/home.jsp) database
## `Makefile` - downloads list of SNPs
## ToDo: Need to process this file into separate disease-specific BED files, rsIDs need to be mapped to genomic coordinates
## ==================================================================

all: gwas_snp_lincrna.txt

gwas_snp_lincrna.txt:
	wget http://210.46.85.180:8080/LincSNP/download/gwas_snp_lincrna.txt