all:	bed

# Creates disease/trait-specific .BED files
bed:
	python gwas2bed.py

# Downloads Barabasi network
AllNet3.net:
	wget http://barabasilab.neu.edu/projects/hudine/resource/datasets/AllNet3.net
