---
title: "Untitled"
author: "Mikhail G. Dozmorov"
date: "May 14, 2015"
output: html_document
---
```{r setup, echo=FALSE, include=FALSE, cache=FALSE, warning=FALSE, message=FALSE}
# Set up the environment
library(knitr) 
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=F, tidy=T, fig.keep='high', dpi=100,  echo=F, autodep=T, width=200, warning=FALSE, comment=NA)
options(replace.assign=TRUE, width=500)
tidy.opts=list(width.cutoff=200)
suppressMessages(library(pander))
panderOptions('table.split.table', Inf)
set.seed(1)
```

```{r message=FALSE}
library(xlsx)
# Load term mapping
term.mapping <- read.xlsx2("data/icd9_mapping.xlsx", sheetName="manual")
#term.mapping <- term.mapping[ term.mapping$Category == "immunological", ]
invisible(source("../../../../GenomeRunner/R.GenomeRunner/utils1.R")) # See the required packages there
source("../../../../GenomeRunner/R.GenomeRunner/episimilarity.R")
# Correlation to use
cortype <- "pearson"
```

```{r}
library(NMF)

mtx <- as.matrix(load_gr_data(c("data.gr/Roadmap_broadPeak/matrix_OR.txt", "data.gr/Roadmap_DNase_hotspotbroadall/matrix_OR.txt")))
mtx <- 2^mtx

annCol.category <- term.mapping$Category[ match(colnames(mtx), term.mapping$Name)]
annCol.size <- as.numeric(term.mapping$BEDcount[ match(colnames(mtx), term.mapping$Name)])

# perform 10 runs for each value of r in range 2:6
estim.r <- nmf(mtx, 2:6, nrun = 10, seed = 123456)
plot(estim.r)

dev.off()
par(mfrow=c(2, 3))
consensusmap(estim.r, annCol = list(annCol.category, annCol.size), labCol = NA)

# How coefficients cluster at rank 3
dev.off()
res <- nmf(mtx, 3)
mtx.heat <- coefmap(res, annCol = list(annCol.category, annCol.size), annColors = list(c("red", "blue", "green", "yellow"), "Reds"))

# We see some diseases with relatively low number of SNPs are outliers. Let's exclude them
diseases.to.exclude <- c("Systemic_sclerosis", "Autoimmune_thyroiditis", "Creatinine_levels")
# After excluding those, we note another diseases with low number of SNPs, that also look outliers. Excluding them
diseases.to.exclude <- c(diseases.to.exclude, "Restless_legs_syndrome", "Kawasaki_disease", "Migraine")
mtx <- mtx[ , !(colnames(mtx) %in% diseases.to.exclude)]
annCol.category <- term.mapping$Category[ match(colnames(mtx), term.mapping$Name)]
annCol.size <- as.numeric(term.mapping$BEDcount[ match(colnames(mtx), term.mapping$Name)])

# perform 10 runs for each value of r in range 2:6
estim.r <- nmf(mtx, 2:6, nrun = 10, seed = 123456)
plot(estim.r)

dev.off()
par(mfrow=c(2, 3))
consensusmap(estim.r, annCol = list(annCol.category, annCol.size), labCol = NA)

# How coefficients cluster at rank 4
dev.off()
res <- nmf(mtx, 4)
mtx.heat <- coefmap(res, annCol = list(annCol.category, annCol.size), annColors = list(c("red", "blue", "green", "yellow"), "Reds"))
basismap(res)

consensusmap(res, annCol = list(annCol.category, annCol.size), annColors = list(c("red", "blue", "green", "yellow"), "Reds"))

# Construct heatmap manually
h <- coef(res)
mtx.heat <- aheatmap(h, annCol = list(annCol.category, annCol.size), annColors = list(c("red", "blue", "green", "yellow"), "Reds"))
```

