---
title: "Figure Full clustergram and tSNE"
author: "Mikhail G. Dozmorov"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, echo=FALSE, include=FALSE, cache=FALSE, warning=FALSE, message=FALSE, eval=TRUE}
# Set up the environment
library(knitr) 
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=F, tidy=T, fig.keep='high', dpi=100,  echo=F, autodep=T, width=200, warning=FALSE, comment=NA, results='hide', eval=FALSE) # Need to explicitly set eval=TRUE for chunks
set.seed(1)
# Local functions and settings
library(MDmisc)
library(dplyr)
# Correlation to use
cortype <- "spearman"
# Clustering: "ward.D", "ward.D2", "single", "complete", "average" (= UPGMA), "mcquitty" (= WPGMA), "median" (= WPGMC) or "centroid" (= UPGMC)
hclust.method <- "ward.D2"
# Color scheme
col3 <- colorRampPalette(c("blue", "yellow", "red"))
```

### Load the data

```{r eval=TRUE}
library(xlsx)
# Load term mapping
term.mapping <- read.xlsx2("data/icd9_mapping.xlsx", sheetName="manual")
# Load the actual episimilarity data
fname <- c("data.gr.05/grweb_roadmapHistone_gPk-imputed/matrix_PVAL.txt", "data.gr.05/grweb_roadmapDNase_gPk-imputed/matrix_PVAL.txt") # Best correlation results
# fname <- c("data.gr.05/grweb_roadmapDNase_gPk-imputed//matrix_PVAL.txt", "data.gr.05/grweb_roadmapDNase_nPk-imputed//matrix_PVAL.txt", "data.gr.05/grweb_roadmapHistone_gPk-imputed//matrix_PVAL.txt", "data.gr.05/grweb_roadmapHistone_nPk-imputed//matrix_PVAL.txt") # Imputed-ALL
# fname <- c("data.gr.05/grweb_roadmapDNase_bPk-processed//matrix_PVAL.txt", "data.gr.05/grweb_roadmapDNase_nPk-processed//matrix_PVAL.txt", "data.gr.05/grweb_roadmapHistone_bPk-processed//matrix_PVAL.txt", "data.gr.05/grweb_roadmapHistone_gPk-processed//matrix_PVAL.txt", "data.gr.05/grweb_roadmapHistone_nPk-processed//matrix_PVAL.txt") # Processed-ALL
# fname <- c("data.gr.05/grweb_encBroadHmm//matrix_PVAL.txt", "data.gr.05/grweb_encChromCombined//matrix_PVAL.txt", "data.gr.05/grweb_encChromHmm//matrix_PVAL.txt", "data.gr.05/grweb_encDNase//matrix_PVAL.txt", "data.gr.05/grweb_encHistone//matrix_PVAL.txt", "data.gr.05/grweb_encSegway//matrix_PVAL.txt", "data.gr.05/grweb_encTFBS_cellspecific//matrix_PVAL.txt", "data.gr.05/grweb_encTFBS_clustered//matrix_PVAL.txt", "data.gr.05/grweb_roadmapChrom15//matrix_PVAL.txt", "data.gr.05/grweb_roadmapChrom18//matrix_PVAL.txt", "data.gr.05/grweb_roadmapChrom25//matrix_PVAL.txt", "data.gr.05/grweb_roadmapDNase_bPk-processed//matrix_PVAL.txt", "data.gr.05/grweb_roadmapDNase_gPk-imputed//matrix_PVAL.txt", "data.gr.05/grweb_roadmapDNase_nPk-imputed//matrix_PVAL.txt", "data.gr.05/grweb_roadmapDNase_nPk-processed//matrix_PVAL.txt", "data.gr.05/grweb_roadmapHistone_bPk-processed//matrix_PVAL.txt", "data.gr.05/grweb_roadmapHistone_gPk-imputed//matrix_PVAL.txt", "data.gr.05/grweb_roadmapHistone_gPk-processed//matrix_PVAL.txt", "data.gr.05/grweb_roadmapHistone_nPk-imputed//matrix_PVAL.txt", "data.gr.05/grweb_roadmapHistone_nPk-processed//matrix_PVAL.txt") # Complete-ALL
mtx <- gr_load_data(fname, p2z = T)
mtx <- mtx[, match(term.mapping$BED, colnames(mtx))] # Match and subset the data
# A vector of category names, same order as the correlation matrix
categoryNames <- term.mapping$Category
names(categoryNames) <- term.mapping$Name
# Trim column names
colnames(mtx) <- term.mapping$Name
```

The -log10-transformed data is transposed to have 39 diseases as rows and 3972 GFs as columns, and saved in `data/mtx_PCA_bestimputed.txt`

```{r eval=FALSE}
write.table(t(mtx), "data/mtx_PCA_bestimputed.txt", sep = "\t", col.names = NA, quote = FALSE)
```


The matrix is scaled, so the enrichment profiles for each disease/phenotype have mean = 0 and SD = 1. 

```{r eval=TRUE}
# mtx.scaled <- mtx %>% t %>% scale %>% t # Row-wise (feature-wise) centering
mtx.scaled <- mtx %>% scale # Column-wise (sample-wise) centering
```

### tSNE

```{r eval = TRUE, fig.height=6, fig.width=6}
library(Rtsne)
term.mapping$Category <- factor(term.mapping$Category)
colors = rainbow(length(unique(term.mapping$Category)))
names(colors) <- unique(term.mapping$Category)
## Executing the algorithm on curated data
tsne <- Rtsne(t(mtx.scaled), dims = 2, perplexity=10, verbose=TRUE, max_iter = 500)

## Plotting
plot(tsne$Y, t='n', main="tsne")
text(tsne$Y, labels=term.mapping$Category, col=colors[term.mapping$Category])
```

```{r eval=TRUE, fig.height=9, fig.width=11}
library(ggplot2)
library(ggrepel)
scores <- as.data.frame(tsne$Y)
rownames(scores) <- colnames(mtx.scaled)
colnames(scores) <- c("Comp.1", "Comp.2")
scores <- left_join(data.frame(Name=rownames(scores), scores), data.frame(Name=names(categoryNames), Category=categoryNames), by = c("Name" = "Name"))
scores$Name <- gsub("_", " ", scores$Name)
pt <- ggplot(data=scores, aes(x=Comp.1, y=Comp.2, label=Name, color = Category)) +
#  labs(x = "PC1 (23.06%)", y = "PC2 (7.95%)") +
  theme(plot.title = element_text(lineheight = 0.8, face="bold")) +
  theme(legend.position = c(0.1, 0.12)) +
  theme(legend.text = element_text(size = 15)) +
  theme(legend.key.size = unit(10, "mm")) +
  geom_point(aes(shape = Category), size = 4) +
  geom_hline(yintercept = 0, colour = "gray65") +
  geom_vline(xintercept = 0, colour = "gray65") +
  geom_text_repel(colour = "black", size = 5)
plot(pt)
# ggtitle("PCA of the regulatory similarities") + 
ggsave(filename="results/Figure_tSNE_bestimputed.pdf", plot=pt, height = 9)
```
