## ==================================================================
## Curated list of disease-associated SNPs (SNPs in LD removed) from
## [PubMed](http://www.ncbi.nlm.nih.gov/pubmed/24390342)
## `Makefile` - downloads list of SNPs
## ToDo: Need to process this file into separate disease-specific BED files, rsIDs need to be mapped to genomic coordinates
## ==================================================================

all: gwas_snp_lincrna.txt

gwas_snp_lincrna.txt:
	wget http://plaza.umin.ac.jp/~yokada/datasource/files/Gwascatalog_20130131.xlsx